[package]
name = "ptn-dataset-gen"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ptn = { version = "0.1.0", path = "../ptn" }
csv = "1.3.0"
rand = "0.8.5"
serde = "1.0.193"
rayon = "1.8.0"