[package]
name = "hello_world" # the name of the package
version = "0.1.0"    # the current version, obeying semver
authors = ["Alice <a@example.com>", "Bob <b@example.com>"]

[lib]
crate-type = ["staticlib"]

[dependencies]
nalgebra = "0.29.0"
libc = "0.2.112"